<?php

namespace ContainerWIW2x4Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator__QZb1Mm_ThrowableService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator..QZb1Mm.Throwable' shared service.
     *
     * @return \Throwable
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..QZb1Mm": it references interface "Throwable" but no such service exists. Did you create a class that implements this interface?');
    }
}
