<?php

namespace ContainerWIW2x4Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerhandleErrorService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator..QZb1Mm.App\Controller\HomeController::handleError()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..QZb1Mm.App\\Controller\\HomeController::handleError()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exception' => ['privates', '.errored..service_locator..QZb1Mm.Throwable', NULL, 'Cannot autowire service ".service_locator..QZb1Mm": it references interface "Throwable" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'exception' => 'Throwable',
        ]))->withContext('App\\Controller\\HomeController::handleError()', $container);
    }
}
