<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWatVgLs\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWatVgLs/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWatVgLs.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWatVgLs\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerWatVgLs\App_KernelProdContainer([
    'container.build_hash' => 'WatVgLs',
    'container.build_id' => '71f09e8a',
    'container.build_time' => 1740348901,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWatVgLs');
