<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWIW2x4Q\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWIW2x4Q/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWIW2x4Q.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWIW2x4Q\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerWIW2x4Q\App_KernelProdContainer([
    'container.build_hash' => 'WIW2x4Q',
    'container.build_id' => 'ca846a34',
    'container.build_time' => 1735484174,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWIW2x4Q');
