<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBHjvbm8\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBHjvbm8/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerBHjvbm8.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerBHjvbm8\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerBHjvbm8\App_KernelProdContainer([
    'container.build_hash' => 'BHjvbm8',
    'container.build_id' => 'ddbf2a79',
    'container.build_time' => 1741039710,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBHjvbm8');
