<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCNon0V5\App_KernelDEVDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCNon0V5/App_KernelDEVDebugContainer.php') {
    touch(__DIR__.'/ContainerCNon0V5.legacy');

    return;
}

if (!\class_exists(App_KernelDEVDebugContainer::class, false)) {
    \class_alias(\ContainerCNon0V5\App_KernelDEVDebugContainer::class, App_KernelDEVDebugContainer::class, false);
}

return new \ContainerCNon0V5\App_KernelDEVDebugContainer([
    'container.build_hash' => 'CNon0V5',
    'container.build_id' => '9d29cb77',
    'container.build_time' => 1732370637,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCNon0V5');
