<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHXEUzB2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHXEUzB2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHXEUzB2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHXEUzB2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHXEUzB2\App_KernelDevDebugContainer([
    'container.build_hash' => 'HXEUzB2',
    'container.build_id' => '23f3d17d',
    'container.build_time' => 1735047062,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHXEUzB2');
