<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.8ab7f0c8.js',
                '/build/725.da8212b2.js',
                '/build/app.7d2ac4d8.js',
            ],
            'css' => [
                '/build/725.956b0c03.css',
                '/build/app.2a7bf991.css',
            ],
        ],
    ],
],

]];
